### ISSUE TITLE
Bugs on calling updateGenerator?

### ISSUE THREAD

**Issue by jeasinema** [SunnerLi/RecycleGAN#2]
Related code [here](https://github.com/SunnerLi/RecycleGAN/blob/master/lib/model/recycle_gan.py#L248-249).
I think the `4th` parameter for these 2 callings should be `fake_b_frame_list[-1]` and `fake_a_frame_list[-1]` respectively since here the loss should be computed with the frames generated by the generator instead of directly derived from ground truth.

**Comment by SunnerLi** [comment]
Hi @jeasinema ,
thanks for your advise!
Actually, this is really my fault.
The function of the `4th` parameter is to provide the gradient of adversarial loss to the generator.
It is not correct to give ground truth to compute the adversarial loss.


After you find this issue, I have revise this part and do the experiments again.
Unfortunately, the performance of correct version drop a lot.
It's please to welcome any advice to raise the performance.
Or maybe wait for author to release their official implementation.


I still provide this mistake version in `perfect` branch. 
The newest version has been deployed into `develop` branch,
and I will push the correct version into `master` branch right away.


Welcome to re-open the issue if you have any problem :-)
